name: Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.1", "3.2", "3.3", "3.4"]
        rails: ["7.2", "8.0"]
        exclude:
          - ruby: "3.1"
            rails: "8.0"
    env:
      RAILS_VERSION: ${{ matrix.rails }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          rm Gemfile.lock
          bundle install

      - name: Run tests
        run: bundle exec rspec
